import type { Metadata } from "next";
import '../styles/main.scss'
import { poppins } from "./fonts";

export const metadata: Metadata = {
  title: "Frontend Mentor | Four card feature section",
  description: "Four card feature section generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.variable}>
      <body>
        {children}
      </body>
    </html>
  );
}
